---
galaxy_info:
  author: HaPe
  description: Java 8 from OpenJDK
  company: HAW Hamburg
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  galaxy_tags:
    - development
    - system
dependencies: []
